DIFFER COMMON.SCM=COMMON.D10,COMMON.MAC/COMMENT
DIFFER ERRCON.SCM=ERRCON.D10,ERRCON.MAC/COMMENT
DIFFER FILIO.SCM=FILIO.D10,FILIO.MAC/COMMENT
DIFFER ONCE.SCM=ONCE.D10,ONCE.MAC/COMMENT
DIFFER S.SCM=S.D10,S.MAC/COMMENT
DIFFER SCNSER.SCM=SCNSER.D10,SCNSER.MAC/COMMENT
DIFFER SWAMP.SCM=SWAMP.D10,SWAMP.MAC/COMMENT
DIFFER UUOCON.SCM=UUOCON.D10,UUOCON.MAC/COMMENT
