#TEXT

VAR1=LINE 1 SCAN "PAGE" SKIP BLANK NUMBER
VAR2=LINE 2 SCAN "SYMBOL TABLE"="S";
	!"SYMBOL CROSS REFERENCE" ="C";
	!"MACRO/OPDEF CROSS REFERENCE"="M";
	!"OPCODE CROSS REFERENCE"="O"
VAR3=LINE FIRST AFTER 2 START 1 FOR 6 STOP AFTER ITEM
VAR4=LINE LAST AFTER 2 START 1 FOR 6 STOP AFTER ITEM
VAR5=IF VAR4 [VAR4]+IFNO VAR4 [VAR5]
VAR6=IF VAR4 [VAR2]+IFNO VAR4 [VAR6]
OUTVAR=IFNO VAR2 [;
	TITLE+","+VAR4+","+LOC+","+VAR1]

#PAGE

KEEP VAR6
KEEP VAR5

#OVERFLOW PAGE

KEEP VAR1
KEEP VAR2
KEEP VAR4
KEEP VAR5
KEEP VAR6
BLANK 3

#INDEX

HEADING "NAME    INDEX     PAGE  LOC"

ITEM 1 SIZE 6 TITLE SUPRESS UNCHANGED
LOCATE 9
ITEM 2 SIZE 6 VAR3
LOCATE 17
ITEM 3 SIZE 1 VAR2
LOCATE 20
ITEM 4 SIZE 3 VAR1 RIGHT
LOCATE 25
ITEM 5 SIZE 4 LOC

#FICHE

REVERSE

GROUP FRAMES 2 CHARACTERS 3 LINES 1 IF GLOBAL START 7 FOR 6 [;
	CHARACTERS 4 IF GLOBAL START 9 FOR 4 [FRAMES 3 CHARACTERS 3;
	IF GLOBAL START 10 FOR 3 [CHARACTERS 4]]]
	TLINE 1 SIZE 12 GLOBAL

GROUP FRAMES 1 LINES 0 IF GLOBAL START 9 FOR 4 [FRAMES 0]

GROUP FRAMES 9 LINES 1 IF TITLE4 [LINES 2] CHARACTERS 3
	TLINE 1 SIZE 24 TITLE1+IF TITLE2 [","+TITLE2+IF TITLE3 [;
		","+TITLE3]] CENTER
	TLINE 2 SIZE 24 IF TITLE4 [TITLE4+IF TITLE5 [","+TITLE5+;
		IF TITLE6 [","+TITLE6]]] CENTER

GROUP FRAMES 2 LINES 2
	TLINE 1 SIZE 6 DAY+"-"+MON3 CENTER
	TLINE 2 SIZE 6 YEAR CENTER

GROUP FRAMES 2 IFNO GLOBAL [LINES 0]
	TLINE 1 SIZE 6 FICHEN RIGHT

#OVERFLOW FICHE

REVERSE

GROUP FRAMES 2 CHARACTERS 3 LINES 1 IF GLOBAL START 7 FOR 6 [;
	CHARACTERS 4 IF GLOBAL START 9 FOR 4 [FRAMES 3 CHARACTERS 3;
	IF GLOBAL START 10 FOR 3 [CHARACTERS 4]]]
	TLINE 1 SIZE 12 GLOBAL

GROUP FRAMES 1 LINES 0 IF GLOBAL START 9 FOR 4 [FRAMES 0]

GROUP FRAMES 4 LINES 1 CHARACTERS 3
	TLINE 1 SIZE 9 TITLE RIGHT
		SIZE 3 "-"+BREAKN

GROUP FRAMES 3 LINES 2
	TLINE 1 SIZE 3 " "+INDEX ITEM 3 PAGE 1
		SIZE 6 INDEX ITEM 2 PAGE 1
	TLINE 2 SIZE 3 " "+VAR6
		SIZE 6 VAR5

GROUP FRAMES 2 LINES 0
	TLINE 1

GROUP FRAMES 2 LINES 2
	TLINE 1 SIZE 6 DAY+"-"+MON3 CENTER
	TLINE 2 SIZE 6 YEAR CENTER

GROUP FRAMES 2 IFNO GLOBAL [LINES 0]
	TLINE 1 SIZE 6 FICHEN RIGHT

#NFILE

REVERSE

GROUP FRAMES 1 IFNO TITLE2 [FRAMES 0] CHARACTERS 3 LINES 2
	TLINE 1 SIZE 3 TITLE START 1 FOR 3
	TLINE 2 SIZE 3 TITLE START 4 FOR 3

#END
