 "/PEKCHK.PAT - Fix stopcode PCBFL1 caused by ill mem ref in PEEK uuo./
UUOCON:
PEKCHK+2/CAIL PG,20
PEKCHK+3/CAML PG,MEMSIZ
PEKCHK+4/POPJ P,
PEKCHK+5/LSH PG,-11
PEKCHK+6/CAMGE PG,SYSSZP
PEKCHK+7/TDZA T3,T3
PEKCHK+10/LDB T3,PGYNXM
