 "\ Patch #9 WAIT1.PAT 28-Oct-88 JMS (for D34 debugging only) \
 "\ Complain if IOACT is set on a DSK ddb. \
CLOCK1:
PAT/WAIT0X:HRRZ S,DEVSER(F)
.+1/CAIE S,DSKDSP
.+1/JRST WAIT1
.+1/MOVEI S,IOACT
.+1/ANDCAM S,DEVIOS(F)
.+1/WAIT1X:XCT .+1
.+1/PUSHJ P,DIE
.+1/"/WAIT1X/
.+1/S$JOB,,WAIT1
.+1/PAT:
WAIT1+4/JRST WAIT0X

COMMON:
PATSIZ/PAT
PATMAP[Q+000400000000
PATMAP[
CONFIG+2T/
