"/PATCH #3: Skip CONO PI,REQCLK at KEYSET+6 while in STOPCD processor/
PICON:
PAT/SETOM TIMEF
PAT+1/SETOM CLKFLG
PAT+2/JRST KEYSET+5
KEYSET+4/JRST PAT
KEYSET+5/SKIPN .CPCPC
PAT+3/PAT:
PATSIZ/PAT
COMMON:
PATMAP[Q+040000000000
CONFIG+1T/
CONFIG+2T/
